### ISSUE TITLE
Publish latest commit to PyPI

### ISSUE THREAD

**Issue by bjoveski** [geminipy/geminipy#14]
Hello Marzig,

Would you mind pushing the latest code with the fix for python 3.6 encoding to PyPI?

Thanks,
Bojan

**Comment by marzig76** [comment]
Yea, probably a good idea thanks.

I'll probably get to it this weekend.

**Comment by marzig76** [comment]
I merged a couple new changes, updated the version number, and published the latest version to PyPi.  I also tested it by installing it from pip and everything worked.

**Comment by bjoveski** [comment]
Awesome, thank you a lot!
